apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: netshoot-secret
  namespace: kube-system
spec:
  provider: aws
  secretObjects:
  - data:
    - key: username
      objectName: "dbpassword"
      objectType: "ssmparameter"
    secretName: netshoot
    type: Opaque

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netshoot
  namespace: kube-system
  labels:
    app: netshoot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netshoot
  template:
    metadata:
      labels:
        app: netshoot
    spec:
      serviceAccountName: external-dns
      containers:
      - name: netshoot
        image: nicolaka/netshoot
        command: ["tail","-f","/dev/null"]
        env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: netshoot
              key: username