apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: netshoot-secret
  namespace: kube-system
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "dbpassword"
        objectType: "ssmparameter"
        jmesPath:
        - path: "username"
          objectAlias: "username"
        - path: "password"
          objectAlias: "password"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netshoot
  namespace: kube-system
  labels:
    app: netshoot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netshoot
  template:
    metadata:
      labels:
        app: netshoot
    spec:
      serviceAccountName: netshoot
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: netshoot-secret
      containers:
      - name: netshoot
        image: nicolaka/netshoot
        command: ["tail","-f","/dev/null"]
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true